home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

home3/urls.py
from django.urls import path

from . import views

app_name = 'home3'

urlpatterns = [
    path('', views.index, name='index'),
    path('table', views.table, name='table'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/', views.delete, name='hapus'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home2/', include('home2.urls')),
    path('home3/', include('home3.urls')),
    path('home4/', include('home4.urls')),
    path('home5/', include('home5.urls')),
    path('home6/', include('home6.urls')),
    path('home7/', include('home7.urls')),
    path('home7/', include('django.contrib.auth.urls')),
]

home3/models.py
from django.db import models

# Create your models here.


class Lessons(models.Model):
    matkul = models.CharField(
        blank=False, max_length=100, help_text="Nama Mata Kuliah")
    dosen = models.CharField(blank=False, max_length=100,
                             help_text="Nama Dosen Mata Kuliah")
    sks = models.IntegerField(
        blank=False, help_text="Jumlah SKS")
    description = models.TextField(
        blank=False, max_length=200, help_text="Sedikit mengenai Mata Kuliah")
    semester_year = models.CharField(
        blank=False, max_length=100,
        help_text="Semester/tahun (E.x Gasal 2020/2021)")
    kelas = models.CharField(
        blank=False, max_length=100,
        help_text="Ruangan matkul diajarkan")

home3/forms.py
from django import forms

from .models import Lessons


class Formulir(forms.Form):
    matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Mata Kuliah',
        'type': 'text',
        'required': True,
        'class': 'input'
    }))

    dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Dosen Mata Kuliah',
        'type': 'text',
        'required': True,
        'class': 'input'
    }))

    sks = forms.IntegerField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jumlah SKS',
        'type': 'text',
        'required': True,
        'class': 'input'
    }))

    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Sedikit mengenai Mata Kuliah',
        'type': 'text',
        'required': True,

        'class': 'input'
    }))

    semester_year = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Semester/tahun (E.x Gasal 2020/2021)',
        'type': 'text',
        'required': True,
        'class': 'input'

    }))

    kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Ruangan matkul diajarkan',
        'type': 'text',
        'required': True,
        'class': 'input'

    }))

home3/views.py
from django.shortcuts import render, redirect
from . import forms, models

# Create your views here.


def index(request):
    if(request.method == "POST"):
        context = forms.Formulir(request.POST)
        if(context.is_valid()):
            context1 = models.Lessons()
            context1.matkul = context.cleaned_data["matkul"]
            context1.dosen = context.cleaned_data["dosen"]
            context1.sks = context.cleaned_data["sks"]
            context1.description = context.cleaned_data["description"]
            context1.semester_year = context.cleaned_data["semester_year"]
            context1.kelas = context.cleaned_data["kelas"]
            context1.save()
        return redirect("/home3/")
    else:
        context = forms.Formulir()
        context1 = models.Lessons.objects.all()
        context_dictio = {
            'Formulir': context,
            'jadwal': context1
        }
    return render(request, 'home3/index.html', context_dictio)


def table(request):
    context = forms.Formulir()
    context1 = models.Lessons.objects.all()
    context_dictio = {
        'Formulir': context,
        'jadwal': context1
    }
    return render(request, 'home3/table.html', context_dictio)


def detail(request, pk):
    something = models.Lessons.objects.get(id=pk)
    context = {
        "pass_name": something
    }
    return render(request, 'home3/detail.html', context)


def delete(request, pk):
    if(request.method == "POST"):
        context = forms.Formulir(request.POST)
        if(context.is_valid()):
            context1 = models.Lessons()
            context1.matkul = context.cleaned_data["matkul"]
            context1.dosen = context.cleaned_data["dosen"]
            context1.sks = context.cleaned_data["sks"]
            context1.description = context.cleaned_data["description"]
            context1.semester_year = context.cleaned_data["semester_year"]
            context1.kelas = context.cleaned_data["kelas"]
            context1.save()
        return redirect("/home3/table")
    else:
        models.Lessons.objects.filter(pk=pk).delete()
        context = forms.Formulir()
        context1 = models.Lessons.objects.all()
        context_dictio = {
            'Formulir': context,
            'jadwal': context1
        }
    return render(request, 'home3/table.html', context_dictio)

home3/templates/home3/detail.html
{% extends "templates/base.html" %}

{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Sora:300,400,500,600,700&display=swap" rel="stylesheet">
<title>Story-5</title>
{% endblock meta %}

    {% block navlist %}
      <a href="/home3/" class="navbar-item">Create Something</a>
      <a href="/home3/table" class="navbar-item">List</a>
{% endblock navlist %}


{% block content %}
        <label class="label">Course Name</label>
        <div class="control py-3">{{ pass_name.matkul }}</div>
        <label class="label">Lecturer's Name</label>
        <div class="control py-3">{{ pass_name.dosen }}</div>
        <label class="label">Credit Score</label>
        <div class="control py-3">{{ pass_name.sks }}</div>
        <label class="label">Description</label>
        <div class="control py-3">{{ pass_name.description }}</div>
        <label class="label">Term</label>
        <div class="control my-3">{{ pass_name.semester_year }}</div>
        <label class="label">Course Room</label>
        <div class="control py-3">{{ pass_name.kelas }}</div>
        <a  href = "/home3/table">
            <div><input class="button is-success" value="Return" /></div>
        </a>
{% endblock content %}

home3/templates/home3/index.html
{% extends "templates/base.html" %}

{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Sora:300,400,500,600,700&display=swap" rel="stylesheet">
<title>Story-5</title>
{% endblock meta %}
    {% block navlist %}
      <a href="/home3" class="navbar-item">Create Something</a>
      <a href="/home3/table" class="navbar-item">List</a>
    {% endblock navlist %}

{% block content %}
<section class="section">
    <div class="container">
      <div class="field">
        <form method="POST">
        {% csrf_token %}
        <label class="label">Course Name</label>
        <div class="control py-3">{{ Formulir.matkul }}</div>
        <label class="label">Lecturer's Name</label>
        <div class="control py-3">{{ Formulir.dosen }}</div>
        <label class="label">Credit Score</label>
        <div class="control py-3">{{ Formulir.sks }}</div>
        <label class="label">Description</label>
        <div class="control py-3">{{ Formulir.description }}</div>
        <label class="label">Term</label>
        <div class="select my-3">{{ Formulir.semester_year }}</div>
        <label class="label">Course Room</label>
        <div class="control py-3">{{ Formulir.kelas }}</div>
        <div class="control py-3"><input class="button is-success" type='submit' value="Save" /></div>
      </form>
    </div>
    </div>
  </section>
{% endblock content %}

home3/templates/home3/table.html
{% extends "templates/base.html" %}

{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Sora:300,400,500,600,700&display=swap" rel="stylesheet">
<title>Story-5</title>
{% endblock meta %}

    {% block navlist %}
      <a href="/home3/" class="navbar-item">Create Something</a>
      <a href="/home3/table" class="navbar-item">List</a>
    {% endblock navlist %}

{% block content %}
<section class="section">
    <div class="container">
    <div class="table-container">
        <table class="table is-fullwidth">
            <thead>
                    <tr>
                    <td>Matkul</td>
                    <td>Dosen</td>
                    <td>SKS</td>
                    <td>Deskripsi</td>
                    <td>Semester</td>
                    <td>Kelas</td>

                    </tr>
            </thead>
            {% for i in jadwal %}
            <tbody>
                <tr>
                    <td>{{i.matkul}}</td>
                    <td>{{i.dosen}}</td>
                    <td>{{i.sks}}</td>
                    <td>{{i.description}}</td>
                    <td>{{i.semester_year}}</td>
                    <td>{{i.kelas}}</td>
                    <td>
                        <a  href = "{% url 'home3:hapus' pk=i.pk %}">
                            <div><input class="button is-danger" value="Delete" /></div>
                        </a>
                    </td>
                    <td>
                        <a  href = "{% url 'home3:detail' pk=i.pk %}">
                            <div><input class="button is-success" value="Detail" /></div>
                        </a>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
    </div>

</section>
{% endblock content %}